version: '3.8'

services:
  # Backend Flask API 
  backend:
    build: /root/brifix-pos-backend
    container_name: brifix-pos-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  # Frontend Next.js Dashboard
  frontend:
    build: /root/brifix-pos-frontend
    container_name: brifix-pos-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # Next.js configurations
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # You can specify public env configs like backend API URLs here if needed
      - NEXT_PUBLIC_API_URL=http://13.127.115.121:5000/api
    depends_on:
      - backend

  # Redis caching service
  redis:
    image: redis:alpine
    container_name: brifix-pos-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    # command: redis-server --requirepass your_redis_password_if_any
